apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mob-assist-ui.default-config-name" . }}
  labels:
    {{ include "mob-assist-ui.labels" . | nindent 4 }}
data:
  proxy.conf: |
    location /graphql {
      proxy_pass {{ .Values.serverUrl }};
    }
    location /subscription {
      proxy_pass {{ .Values.graphqlUrl }};
    }
