{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "mob-assist-ui.name" . }}
  labels:
    {{ include "mob-assist-ui.labels" . | nindent 4 }}
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: {{ include "mob-assist-ui.fullname" . }}
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{- end }}