apiVersion: v1
kind: Secret
metadata:
  name: {{ include "appid-binding.fullname" . }}
  labels:
    {{- include "appid-binding.labels" . | nindent 4 }}
stringData:
  URL: {{ required "url is required" .Values.url | quote }}
  DISCOVERY_ENDPOINT: {{ required "discoveryEndpoint is required" .Values.discoveryEndpoint | quote}}
  TENANT_ID: {{ required "tenantId is required" .Values.tenantId | quote }}
  CLIENT_ID: {{ required "clientId is required" .Values.clientId | quote }}
  CLIENT_SECRET: {{ required "clientSecret is required" .Values.clientSecret | quote }}
